var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/standards/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__12rfibs._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0g5ykh9.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_11dij6w._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.o7a4o._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/src_0g.-j_l._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_standards_page_actions_0l_2olq.js")
R.m(43130)
module.exports=R.m(43130).exports
